language: "perl"
dist: xenial
os:
  - linux
  - osx

osx_image: xcode7.3

env:
  global:
    - ALIEN_BUILD_PRELOAD=Probe::OverrideCI
  matrix:
    - ALIEN_INSTALL_TYPE_CI=share
    - ALIEN_INSTALL_TYPE_CI=default

jobs:
  exclude:
    - os: osx
      perl: "5.14"

perl:
  - "5.14"
  - "5.26"

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      eval "$($HOME/perl5/perlbrew/bin/perlbrew env $TRAVIS_PERL_VERSION)"
      export PATH=${PERLBREW_PATH:-$PERLBREW_ROOT/bin}:$PATH
      perlbrew --quiet install-cpanm --force
      cpanm --version
      env | grep -i ^perl
      export SSL_DIR=/usr/local/Cellar/openssl/1.0.2j
    fi

install:
  - cpanm -n Alien::Build::Plugin::Probe::OverrideCI
  - cpanm -n --installdeps .
